//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LommeregnerClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Lommeregner")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Plus", ReplyAction="http://tempuri.org/IService1/PlusResponse")]
        double Plus(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Plus", ReplyAction="http://tempuri.org/IService1/PlusResponse")]
        System.Threading.Tasks.Task<double> PlusAsync(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Minus", ReplyAction="http://tempuri.org/IService1/MinusResponse")]
        double Minus(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Minus", ReplyAction="http://tempuri.org/IService1/MinusResponse")]
        System.Threading.Tasks.Task<double> MinusAsync(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gange", ReplyAction="http://tempuri.org/IService1/GangeResponse")]
        double Gange(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gange", ReplyAction="http://tempuri.org/IService1/GangeResponse")]
        System.Threading.Tasks.Task<double> GangeAsync(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Divider", ReplyAction="http://tempuri.org/IService1/DividerResponse")]
        double Divider(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Divider", ReplyAction="http://tempuri.org/IService1/DividerResponse")]
        System.Threading.Tasks.Task<double> DividerAsync(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/All", ReplyAction="http://tempuri.org/IService1/AllResponse")]
        string All(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/All", ReplyAction="http://tempuri.org/IService1/AllResponse")]
        System.Threading.Tasks.Task<string> AllAsync(double value, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        LommeregnerClient.ServiceReference1.CompositeType GetDataUsingDataContract(LommeregnerClient.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<LommeregnerClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(LommeregnerClient.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LommeregnerClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LommeregnerClient.ServiceReference1.IService1>, LommeregnerClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public double Plus(double value, double value2) {
            return base.Channel.Plus(value, value2);
        }
        
        public System.Threading.Tasks.Task<double> PlusAsync(double value, double value2) {
            return base.Channel.PlusAsync(value, value2);
        }
        
        public double Minus(double value, double value2) {
            return base.Channel.Minus(value, value2);
        }
        
        public System.Threading.Tasks.Task<double> MinusAsync(double value, double value2) {
            return base.Channel.MinusAsync(value, value2);
        }
        
        public double Gange(double value, double value2) {
            return base.Channel.Gange(value, value2);
        }
        
        public System.Threading.Tasks.Task<double> GangeAsync(double value, double value2) {
            return base.Channel.GangeAsync(value, value2);
        }
        
        public double Divider(double value, double value2) {
            return base.Channel.Divider(value, value2);
        }
        
        public System.Threading.Tasks.Task<double> DividerAsync(double value, double value2) {
            return base.Channel.DividerAsync(value, value2);
        }
        
        public string All(double value, double value2) {
            return base.Channel.All(value, value2);
        }
        
        public System.Threading.Tasks.Task<string> AllAsync(double value, double value2) {
            return base.Channel.AllAsync(value, value2);
        }
        
        public LommeregnerClient.ServiceReference1.CompositeType GetDataUsingDataContract(LommeregnerClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<LommeregnerClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(LommeregnerClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
